name: Terraform Deployment

on: 
  # push:
  #   branches: 
  #   - main
  # pull_request:
  #   branches:
  #   - main
  workflow_dispatch:
    inputs:
      apply:
          description: 'Are you sure ???'
          required: true
          type: boolean
          default: false

permissions:
  id-token: write
  contents: read

env: 
  AWS_REGION: "ap-south-1"

jobs:
  tf-plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Configure AWS OIDC
      uses: aws-actions/configure-aws-credentials@main
      with: 
        aws-region: ap-south-1
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
        
    - name: Terraform Plan
      uses: hashicorp/setup-terraform@v3
      
    - name: Terraform Init  
      run: terraform init
    
    - name: Terraform Plan
      run: terraform plan 

    - name: Terraform Format
      run: terraform fmt
  
  tf-apply:
    needs: tf-plan
    if: ${{ inputs.apply == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS OIDC
        uses: aws-actions/configure-aws-credentials@main
        with: 
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          
      - name: Terraform Plan
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform Init  
        run: terraform init
      
      - name: Terraform Plan
        run: terraform apply -auto-approve
