name: Terraform Destroy

on: 
  workflow_dispatch: 
    inputs:
        confirm:
            description: "Destroy Infra"
            required: true
            type: string



permissions:
  id-token: write
  contents: read

env: 
  AWS_REGION: "ap-south-1"

jobs:  
  tf-delete:
    if: ${{ inputs.confirm == 'DESTROY'  }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS OIDC
        uses: aws-actions/configure-aws-credentials@main
        with: 
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform Init  
        run: terraform init
      
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
